'use strict';(function(){function z(c){var g,a,e,b=c=="json";if(b||c=="json-stringify"||c=="json-parse"){if(c=="json-stringify"||b){if(g=typeof d.stringify=="function"&&k){(e=function(){return 1}).toJSON=e;try{g=d.stringify(0)==="0"&&d.stringify(new Number)==="0"&&d.stringify(new String)=='""'&&d.stringify(m)===q&&d.stringify(q)===q&&d.stringify()===q&&d.stringify(e)==="1"&&d.stringify([e])=="[1]"&&d.stringify([q])=="[null]"&&d.stringify(null)=="null"&&d.stringify([q,m,null])=="[null,null,null]"&&
d.stringify({A:[e,true,false,null,"\x00\u0008\n\u000c\r\t"]})=='{"A":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'&&d.stringify(null,e)==="1"&&d.stringify([1,2],null,1)=="[\n 1,\n 2\n]"&&d.stringify(new Date(-864E13))=='"-271821-04-20T00:00:00.000Z"'&&d.stringify(new Date(864E13))=='"+275760-09-13T00:00:00.000Z"'&&d.stringify(new Date(-621987552E5))=='"-000001-01-01T00:00:00.000Z"'&&d.stringify(new Date(-1))=='"1969-12-31T23:59:59.999Z"'}catch(j){g=false}}if(!b)return g}if(c=="json-parse"||b){if(typeof d.parse==
"function")try{if(d.parse("0")===0&&!d.parse(false)&&(e=d.parse('{"A":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'),a=e.A.length==5&&e.A[0]==1)){try{a=!d.parse('"\t"')}catch(I){}if(a)try{a=d.parse("01")!=1}catch(f){}}}catch(h){a=false}if(!b)return a}return g&&a}}var m={}.toString,n,A,q,r=typeof define==="function"&&define.amd,d=!r&&typeof exports=="object"&&exports;if(d||r)if(typeof JSON=="object"&&JSON)r?d=JSON:(d.stringify=JSON.stringify,d.parse=JSON.parse);else{if(r)d=this.JSON={}}else d=this.JSON||
(this.JSON={});var B,o,C,y,F,G,i,l,s,D,E,b,t,k=new Date(-3509827334573292),p,H,w;try{k=k.getUTCFullYear()==-109252&&k.getUTCMonth()===0&&k.getUTCDate()==1&&k.getUTCHours()==10&&k.getUTCMinutes()==37&&k.getUTCSeconds()==6&&k.getUTCMilliseconds()==708}catch(J){}if(!z("json")){if(!k)p=Math.floor,H=[0,31,59,90,120,151,181,212,243,273,304,334],w=function(c,g){return H[g]+365*(c-1970)+p((c-1969+(g=+(g>1)))/4)-p((c-1901+g)/100)+p((c-1601+g)/400)};if(!(n={}.hasOwnProperty))n=function(c){var g={},a;(g.__proto__=
null,g.__proto__={toString:1},g).toString!=m?n=function(a){var c=this.__proto__,a=a in(this.__proto__=null,this);this.__proto__=c;return a}:(a=g.constructor,n=function(c){var g=(this.constructor||a).prototype;return c in this&&!(c in g&&this[c]===g[c])});g=null;return n.call(this,c)};A=function(c,g){var a=0,b,d,j;(b=function(){this.valueOf=0}).prototype.valueOf=0;d=new b;for(j in d)n.call(d,j)&&a++;b=d=null;a?a=a==2?function(a,c){var g={},b=m.call(a)=="[object Function]",e;for(e in a)!(b&&e=="prototype")&&
!n.call(g,e)&&(g[e]=1)&&n.call(a,e)&&c(e)}:function(a,c){var g=m.call(a)=="[object Function]",b,e;for(b in a)!(g&&b=="prototype")&&n.call(a,b)&&!(e=b==="constructor")&&c(b);(e||n.call(a,b="constructor"))&&c(b)}:(d="valueOf,toString,toLocaleString,propertyIsEnumerable,isPrototypeOf,hasOwnProperty,constructor".split(","),a=function(a,c){var g=m.call(a)=="[object Function]",b;for(b in a)!(g&&b=="prototype")&&n.call(a,b)&&c(b);for(g=d.length;b=d[--g];n.call(a,b)&&c(b));});return a(c,g)};if(!z("json-stringify"))B=
{"\\":"\\\\",'"':'\\"',"\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},o=function(c,b){return("000000"+(b||0)).slice(-c)},C=function(c){for(var b='"',a=0,e;e=c.charAt(a);a++)b+='\\"\u0008\u000c\n\r\t'.indexOf(e)>-1?B[e]:B[e]=e<" "?"\\u00"+o(2,e.charCodeAt(0).toString(16)):e;return b+'"'},y=function(c,b,a,e,d,j,i){var f=b[c],h,k,l,u,r,s,t,v,x;if(typeof f=="object"&&f)if(h=m.call(f),h=="[object Date]"&&!n.call(f,"toJSON"))if(f>-1/0&&f<1/0){if(w){l=p(f/864E5);for(h=p(l/365.2425)+1970-
1;w(h+1,0)<=l;h++);for(k=p((l-w(h,0))/30.42);w(h,k+1)<=l;k++);l=1+l-w(h,k);u=(f%864E5+864E5)%864E5;r=p(u/36E5)%24;s=p(u/6E4)%60;t=p(u/1E3)%60;u%=1E3}else h=f.getUTCFullYear(),k=f.getUTCMonth(),l=f.getUTCDate(),r=f.getUTCHours(),s=f.getUTCMinutes(),t=f.getUTCSeconds(),u=f.getUTCMilliseconds();f=(h<=0||h>=1E4?(h<0?"-":"+")+o(6,h<0?-h:h):o(4,h))+"-"+o(2,k+1)+"-"+o(2,l)+"T"+o(2,r)+":"+o(2,s)+":"+o(2,t)+"."+o(3,u)+"Z"}else f=null;else if(typeof f.toJSON=="function"&&(h!="[object Number]"&&h!="[object String]"&&
h!="[object Array]"||n.call(f,"toJSON")))f=f.toJSON(c);a&&(f=a.call(b,c,f));if(f===null)return"null";h=m.call(f);if(h=="[object Boolean]")return""+f;else if(h=="[object Number]")return f>-1/0&&f<1/0?""+f:"null";else if(h=="[object String]")return C(f);if(typeof f=="object"){for(c=i.length;c--;)if(i[c]===f)throw TypeError();i.push(f);v=[];b=j;j+=d;if(h=="[object Array]"){for(k=0,c=f.length;k<c;x||(x=true),k++)h=y(k,f,a,e,d,j,i),v.push(h===q?"null":h);c=x?d?"[\n"+j+v.join(",\n"+j)+"\n"+b+"]":"["+v.join(",")+
"]":"[]"}else A(e||f,function(c){var b=y(c,f,a,e,d,j,i);b!==q&&v.push(C(c)+":"+(d?" ":"")+b);x||(x=true)}),c=x?d?"{\n"+j+v.join(",\n"+j)+"\n"+b+"}":"{"+v.join(",")+"}":"{}";i.pop();return c}},d.stringify=function(c,b,a){var e,d,j,i,f,h;if(typeof b=="function"||typeof b=="object"&&b)if(m.call(b)=="[object Function]")d=b;else if(m.call(b)=="[object Array]"){j={};for(i=0,f=b.length;i<f;h=b[i++],(m.call(h)=="[object String]"||m.call(h)=="[object Number]")&&(j[h]=1));}if(a)if(m.call(a)=="[object Number]"){if((a-=
a%1)>0)for(e="",a>10&&(a=10);e.length<a;e+=" ");}else m.call(a)=="[object String]"&&(e=a.length<=10?a:a.slice(0,10));return y("",(h={},h[""]=c,h),d,j,e,"",[])};if(!z("json-parse"))F=String.fromCharCode,G={"\\":"\\",'"':'"',"/":"/",b:"\u0008",t:"\t",n:"\n",f:"\u000c",r:"\r"},i=function(){b=t=null;throw SyntaxError();},l=function(){for(var c=t,g=c.length,a,e,d,j,k;b<g;)if(a=c.charAt(b),"\t\r\n ".indexOf(a)>-1)b++;else if("{}[]:,".indexOf(a)>-1)return b++,a;else{if(a=='"'){for(e="@",b++;b<g;)if(a=c.charAt(b),
a<" ")i();else if(a=="\\")if(a=c.charAt(++b),'\\"/btnfr'.indexOf(a)>-1)e+=G[a],b++;else if(a=="u"){d=++b;for(j=b+4;b<j;b++)a=c.charAt(b),a>="0"&&a<="9"||a>="a"&&a<="f"||a>="A"&&a<="F"||i();e+=F("0x"+c.slice(d,b))}else i();else{if(a=='"')break;e+=a;b++}if(c.charAt(b)=='"')return b++,e}else{d=b;a=="-"&&(k=true,a=c.charAt(++b));if(a>="0"&&a<="9"){for(a=="0"&&(a=c.charAt(b+1),a>="0"&&a<="9")&&i();b<g&&(a=c.charAt(b),a>="0"&&a<="9");b++);if(c.charAt(b)=="."){for(j=++b;j<g&&(a=c.charAt(j),a>="0"&&a<="9");j++);
j==b&&i();b=j}a=c.charAt(b);if(a=="e"||a=="E"){a=c.charAt(++b);(a=="+"||a=="-")&&b++;for(j=b;j<g&&(a=c.charAt(j),a>="0"&&a<="9");j++);j==b&&i();b=j}return+c.slice(d,b)}k&&i();if(c.slice(b,b+4)=="true")return b+=4,true;else if(c.slice(b,b+5)=="false")return b+=5,false;else if(c.slice(b,b+4)=="null")return b+=4,null}i()}return"$"},s=function(c){var b,a;c=="$"&&i();if(typeof c=="string"){if(c.charAt(0)=="@")return c.slice(1);if(c=="["){for(b=[];;a||(a=true)){c=l();if(c=="]")break;a&&(c==","?(c=l(),c==
"]"&&i()):i());c==","&&i();b.push(s(c))}return b}else if(c=="{"){for(b={};;a||(a=true)){c=l();if(c=="}")break;a&&(c==","?(c=l(),c=="}"&&i()):i());(c==","||typeof c!="string"||c.charAt(0)!="@"||l()!=":")&&i();b[c.slice(1)]=s(l())}return b}i()}return c},E=function(b,d,a){a=D(b,d,a);a===q?delete b[d]:b[d]=a},D=function(b,d,a){var e=b[d],i;if(typeof e=="object"&&e)if(m.call(e)=="[object Array]")for(i=e.length;i--;)E(e,i,a);else A(e,function(b){E(e,b,a)});return a.call(b,d,e)},d.parse=function(c,d){var a,
e;b=0;t=c;a=s(l());l()!="$"&&i();b=t=null;return d&&m.call(d)=="[object Function]"?D((e={},e[""]=a,e),"",d):a}}r&&define(function(){return d})}).call(this);
