/*
 console-shim 1.0.2
 https://github.com/kayahr/console-shim
 Copyright (C) 2011 Klaus Reimer <k@ailis.de>
 Licensed under the MIT license
 (See http://www.opensource.org/licenses/mit-license)
*/
'use strict';(function(){for(var a=["ms","moz","webkit","o"],b=0;b<a.length&&!window.requestAnimationFrame;++b)window.requestAnimationFrame=window[a[b]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[a[b]+"CancelAnimationFrame"]||window[a[b]+"CancelRequestAnimationFrame"];if(!window.requestAnimationFrame||!window.cancelAnimationFrame){var c=0;window.requestAnimationFrame=function(a){var b=Date.now(),g=Math.max(0,16-(b-c));c=b+g;return window.setTimeout(function(){a(b+g)},g)};window.cancelAnimationFrame=
function(a){clearTimeout(a)}}})();
"addEventListener"in window||function(){window.addEventListener=function(a,b){attachEvent("on"+a,b)};window.removeEventListener=function(a,b){detachEvent("on"+a,b)};document.addEventListener=function(a,b){var c=false;if(a=="DOMContentLoaded"){var d=function(){document.readyState==="complete"&&(document.detachEvent("onreadystatechange",d),c=true,b())};document.attachEvent("onreadystatechange",d);if(document.documentElement.doScroll&&window==window.top)a:if(!c){try{document.documentElement.doScroll("left")}catch(e){setTimeout(document.addEventListener,0);
break a}c=true;b()}var g=function(){window.removeEventListener("load",g);c||(c=true,b())};window.addEventListener("load",g,false)}else attachEvent("on"+a,b)};document.removeEventListener=function(a,b){a!="DOMContentLoaded"&&detachEvent("on"+a,b)}}();Function.prototype.isGenerator||function(){Function.prototype.isGenerator=function(){return false}}();
navigator.geolocation||function(){function a(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function b(a,b){this.code=a;this.message=b}function c(a){this.accuracy=j*Math.PI;this.heading=this.altitudeAccuracy=this.altitude=null;this.latitude=Number(a.latitude);this.longitude=Number(a.longitude);this.speed=null}function d(a){this.timestamp=Number(new Date);this.coords=new c(a)}function e(){function c(a,b){if(typeof a==="function")setTimeout(function(){a(b)},0);else if(typeof a==="object"&&a&&
"handleEvent"in a)a=a.handleEvent,setTimeout(function(){a(b)},0)}function e(a){function b(){c.parentNode&&c.parentNode.removeChild(c);try{delete window[f]}catch(a){window[f]=void 0}}var c=document.createElement("SCRIPT"),f="_geoip_callback_"+Math.floor(Math.random()*1073741824);window[f]=function(c){b();a(new d(c))};c.onerror=function(){b()};c.src=g+encodeURIComponent(f);(document.head||document.body||document.documentElement).appendChild(c);return b}var n=null;this.getCurrentPosition=function(f,
d,g){if(!f)throw new TypeError("The successCallback parameter is null.");var o;o=g&&a(g,"maximumAge")&&Number(g.maximumAge)>=0?Number(g.maximumAge):0;var h;h=g&&a(g,"timeout")?Number(g.timeout)>=0?Number(g.timeout):0:Infinity;var i;i=g&&a(g,"enableHighAccuracy")?Boolean(i):false;if(n&&Number(new Date)-n.timestamp<o)c(f,n);else if(h===0)c(d,new b(b.TIMEOUT,"Timed out"));else{var j=e(function(a){n=a;x||(u&&clearTimeout(u),c(f,a))},function(){x||(u&&clearTimeout(u),c(d,new b(b.POSITION_UNAVAILABLE,"Position unavailable")))},
i),x=false,u=0;isFinite(h)&&(u=setTimeout(function(){x=true;j();c(d,new b(b.TIMEOUT,"Timed out"))},h))}};var i=[],o=0;this.watchPosition=function(g,v,p){function j(){var a=e(function(a){n=a;!s&&!A.cleared&&(u&&(clearTimeout(u),u=0),d.distance(x,a)>=m&&(x=a,c(g,a)))},function(){!s&&!A.cleared&&(u&&(clearTimeout(u),u=0),c(v,new b(b.POSITION_UNAVAILABLE,"Position unavailable")))},r),s=false;isFinite(z)&&!u&&(u=setTimeout(function(){s=true;u=0;a();A.cleared||c(v,new b(b.TIMEOUT,"Timed out"))},z))}if(!g)throw new TypeError("The successCallback parameter is null.");
var h;h=p&&a(p,"maximumAge")&&Number(p.maximumAge)>=0?Number(p.maximumAge):0;var z;z=p&&a(p,"timeout")?Number(p.timeout)>=0?Number(p.timeout):0:Infinity;var r;r=p&&a(p,"enableHighAccuracy")?Boolean(r):false;n&&Number(new Date)-n.timestamp<h&&c(g,n);var x=null,u=0;j();var A={intervalId:setInterval(function(){j()},f),cleared:false},p=++o;i[p]=A;return p};this.clearWatch=function(b){b=Number(b);if(a(i,b)){var c=i[b];delete i[b];clearInterval(c.intervalId);c.cleared=true}}}var g="http://freegeoip.net/json/google.com?callback=",
f=1E3/(1E3/3600)*2,m=20,j=6384E3;b.PERMISSION_DENIED=1;b.POSITION_UNAVAILABLE=2;b.TIMEOUT=3;b.prototype=Error();d.distance=function(a,b){var c;if(a===b)c=0;else if(!a||!b)c=Infinity;else{c=j;var e,f=a.coords.latitude,d=b.coords.latitude;e=Math.cos((a.coords.longitude-b.coords.longitude)*Math.PI/180);var g=Math.cos((f-d)*Math.PI/180),f=Math.cos((f+d)*Math.PI/180);e=Math.acos((e*(g+f)+(g-f))/2);c*=e}return c};if(!navigator.geolocation)navigator.geolocation=new e,window.PositionError=b}();
window.localStorage||function(){window.localStorage={getItem:function(a){return!a||!this.hasOwnProperty(a)?null:unescape(document.cookie.replace(RegExp("(?:^|.*;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1"))},key:function(a){return unescape(document.cookie.replace(/\s*\=(?:.(?!;))*$/,"").split(/\s*\=(?:[^;](?!;))*[^;]?;\s*/)[a])},setItem:function(a,b){if(a)document.cookie=escape(a)+"="+escape(b)+"; path=/",this.length=document.cookie.match(/\=/g).length},
length:0,removeItem:function(a){if(a&&this.hasOwnProperty(a)){var b=new Date;b.setDate(b.getDate()-1);document.cookie=escape(a)+"=; expires="+b.toGMTString()+"; path=/";this.length--}},hasOwnProperty:function(a){return RegExp("(?:^|;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=").test(document.cookie)}};window.localStorage.length=(document.cookie.match(/\=/g)||window.localStorage).length}();
Object.create||function(){Object.create=function(a,b){var c;if(a===null)c={__proto__:null};else{if(typeof a!="object")throw new TypeError("typeof prototype["+typeof a+"] != 'object'");c=function(){};c.prototype=a;c=new c;c.__proto__=a}b!==void 0&&Object.defineProperties(c,b);return c}}();Object.defineProperties||function(){Object.defineProperties=function(a,b){for(var c in b)b.hasOwnProperty(c)&&c!="__proto__"&&Object.defineProperty(a,c,b[c]);return a}}();
(function(){var a=Object.prototype.hasOwnProperty("__defineGetter__")&&Object.prototype.hasOwnProperty("__defineSetter__")&&Object.prototype.hasOwnProperty("__lookupGetter__")&&Object.prototype.hasOwnProperty("__lookupSetter__"),b=function(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(b){}},c;if(Object.defineProperty){var d=typeof document=="undefined"||b(document.createElement("div"));if(!b({})||!d)c=Object.defineProperty}if(!Object.defineProperty||c)Object.defineProperty=
function(b,d,f){if(typeof b!="object"&&typeof b!="function"||b===null)throw new TypeError("Object.defineProperty called on non-object: "+b);if(typeof f!="object"&&typeof f!="function"||f===null)throw new TypeError("Property description must be an object: "+f);if(c)try{return c.call(Object,b,d,f)}catch(m){}if(f.hasOwnProperty("value"))if(a&&(b.__lookupGetter__(d)||b.__lookupSetter__(d))){var j=b.__proto__;b.__proto__=Object.prototype;delete b[d];b[d]=f.value;b.__proto__=j}else b[d]=f.value;else{if(!a)throw new TypeError("getters & setters can not be defined on this javascript engine");
f.hasOwnProperty("get")&&b.__defineGetter__(d,f.get);f.hasOwnProperty("set")&&b.__defineSetter__(d,f.set)}return b}})();
Object.getOwnPropertyDescriptor||function(){var a=Object.prototype.hasOwnProperty("__lookupGetter__")&&Object.prototype.hasOwnProperty("__lookupSetter__");Object.getOwnPropertyDescriptor=function(b,c){if(typeof b!="object"&&typeof b!="function"||b===null)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+b);if(b.hasOwnProperty(c)){var d={enumerable:true,configurable:true};if(a){var e=b.__proto__;b.__proto__=Object.prototype;var g=b.__lookupGetter__(c),f=b.__lookupSetter__(c);
b.__proto__=e;if(g||f){if(g)d.get=g;if(f)d.set=f;return d}}d.value=b[c];return d}}}();Object.getOwnPropertyNames||function(){Object.getOwnPropertyNames=function(a){return Object.keys(a)}}();Object.getPrototypeOf||function(){Object.getPrototypeOf=function(a){return a.__proto__||(a.constructor?a.constructor.prototype:Object.prototype)}}();
Object.isExtensible||function(){Object.isExtensible=function(a){if(Object(a)!==a)throw new TypeError;for(var b="";a.hasOwnProperty(b);)b+="?";a[b]=true;var c=a.hasOwnProperty(b);delete a[b];return c}}();
(function(a){typeof define=="function"?define(a):typeof YUI=="function"?YUI.add("es5",a):a()})(function(){function a(){}function b(a){a=+a;a!==a?a=0:a!==0&&a!==1/0&&a!==-(1/0)&&(a=(a>0||-1)*Math.floor(Math.abs(a)));return a}function c(a){var b=typeof a;return a===null||b==="undefined"||b==="boolean"||b==="number"||b==="string"}if(!Function.prototype.bind)Function.prototype.bind=function(b){var c=this;if(typeof c!="function")throw new TypeError("Function.prototype.bind called on incompatible "+c);
var d=g.call(arguments,1),f=function(){if(this instanceof f){var a=c.apply(this,d.concat(g.call(arguments)));return Object(a)===a?a:this}else return c.apply(b,d.concat(g.call(arguments)))};if(c.prototype)a.prototype=c.prototype,f.prototype=new a,a.prototype=null;return f};var d=Function.prototype.call,e=Object.prototype,g=Array.prototype.slice,f=d.bind(e.toString),m=d.bind(e.hasOwnProperty);m(e,"__defineGetter__")&&(d.bind(e.__defineGetter__),d.bind(e.__defineSetter__),d.bind(e.__lookupGetter__),
d.bind(e.__lookupSetter__));if([1,2].splice(0).length!=2){var j=Array.prototype.splice;Array.prototype.splice=function(a,b){return arguments.length?j.apply(this,[a===void 0?0:a,b===void 0?this.length-a:b].concat(g.call(arguments,2))):[]}}if([].unshift(0)!=1){var k=Array.prototype.unshift;Array.prototype.unshift=function(){k.apply(this,arguments);return this.length}}if(!Array.isArray)Array.isArray=function(a){return f(a)=="[object Array]"};var d=Object("a"),q=d[0]!="a"||!(0 in d);if(!Array.prototype.forEach)Array.prototype.forEach=
function(a,b){var c=r(this),d=q&&f(this)=="[object String]"?this.split(""):c,s=-1,e=d.length>>>0;if(f(a)!="[object Function]")throw new TypeError;for(;++s<e;)s in d&&a.call(b,d[s],s,c)};if(!Array.prototype.map)Array.prototype.map=function(a,b){var c=r(this),d=q&&f(this)=="[object String]"?this.split(""):c,s=d.length>>>0,e=Array(s);if(f(a)!="[object Function]")throw new TypeError(a+" is not a function");for(var y=0;y<s;y++)y in d&&(e[y]=a.call(b,d[y],y,c));return e};if(!Array.prototype.filter)Array.prototype.filter=
function(a,b){var c=r(this),d=q&&f(this)=="[object String]"?this.split(""):c,s=d.length>>>0,e=[],y;if(f(a)!="[object Function]")throw new TypeError(a+" is not a function");for(var g=0;g<s;g++)g in d&&(y=d[g],a.call(b,y,g,c)&&e.push(y));return e};if(!Array.prototype.every)Array.prototype.every=function(a,b){var c=r(this),d=q&&f(this)=="[object String]"?this.split(""):c,s=d.length>>>0;if(f(a)!="[object Function]")throw new TypeError(a+" is not a function");for(var e=0;e<s;e++)if(e in d&&!a.call(b,d[e],
e,c))return false;return true};if(!Array.prototype.some)Array.prototype.some=function(a,b){var c=r(this),d=q&&f(this)=="[object String]"?this.split(""):c,s=d.length>>>0;if(f(a)!="[object Function]")throw new TypeError(a+" is not a function");for(var e=0;e<s;e++)if(e in d&&a.call(b,d[e],e,c))return true;return false};if(!Array.prototype.reduce)Array.prototype.reduce=function(a){var b=r(this),c=q&&f(this)=="[object String]"?this.split(""):b,d=c.length>>>0;if(f(a)!="[object Function]")throw new TypeError(a+
" is not a function");if(!d&&arguments.length==1)throw new TypeError("reduce of empty array with no initial value");var s=0,e;if(arguments.length>=2)e=arguments[1];else{do{if(s in c){e=c[s++];break}if(++s>=d)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;s<d;s++)s in c&&(e=a.call(void 0,e,c[s],s,b));return e};if(!Array.prototype.reduceRight)Array.prototype.reduceRight=function(a){var b=r(this),c=q&&f(this)=="[object String]"?this.split(""):b,d=c.length>>>0;if(f(a)!=
"[object Function]")throw new TypeError(a+" is not a function");if(!d&&arguments.length==1)throw new TypeError("reduceRight of empty array with no initial value");var e;d-=1;if(arguments.length>=2)e=arguments[1];else{do{if(d in c){e=c[d--];break}if(--d<0)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}do d in this&&(e=a.call(void 0,e,c[d],d,b));while(d--);return e};if(!Array.prototype.indexOf||[0,1].indexOf(1,2)!=-1)Array.prototype.indexOf=function(a){var c=q&&f(this)==
"[object String]"?this.split(""):r(this),d=c.length>>>0;if(!d)return-1;var e=0;arguments.length>1&&(e=b(arguments[1]));for(e=e>=0?e:Math.max(0,d+e);e<d;e++)if(e in c&&c[e]===a)return e;return-1};if(!Array.prototype.lastIndexOf||[0,1].lastIndexOf(0,-3)!=-1)Array.prototype.lastIndexOf=function(a){var c=q&&f(this)=="[object String]"?this.split(""):r(this),d=c.length>>>0;if(!d)return-1;var e=d-1;arguments.length>1&&(e=Math.min(e,b(arguments[1])));for(e=e>=0?e:d-Math.abs(e);e>=0;e--)if(e in c&&a===c[e])return e;
return-1};if(!Object.keys){var n=true,i="toString,toLocaleString,valueOf,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,constructor".split(","),o=i.length,l;for(l in{toString:null})n=false;Object.keys=function u(a){if(typeof a!="object"&&typeof a!="function"||a===null)throw new TypeError("Object.keys called on a non-object");var u=[],b;for(b in a)m(a,b)&&u.push(b);if(n)for(b=0;b<o;b++){var c=i[b];m(a,c)&&u.push(c)}return u}}if(!Date.prototype.toISOString||(new Date(-621987552E5)).toISOString().indexOf("-000001")===
-1)Date.prototype.toISOString=function(){var a,b,c,d;if(!isFinite(this))throw new RangeError("Date.prototype.toISOString called on non-finite value.");d=this.getUTCFullYear();a=this.getUTCMonth();d+=Math.floor(a/12);a=[(a%12+12)%12+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];d=(d<0?"-":d>9999?"+":"")+("00000"+Math.abs(d)).slice(0<=d&&d<=9999?-4:-6);for(b=a.length;b--;)c=a[b],c<10&&(a[b]="0"+c);return d+"-"+a.slice(0,2).join("-")+"T"+a.slice(2).join(":")+"."+("000"+
this.getUTCMilliseconds()).slice(-3)+"Z"};l=false;try{l=Date.prototype.toJSON&&(new Date(NaN)).toJSON()===null&&(new Date(-621987552E5)).toJSON().indexOf("-000001")!==-1&&Date.prototype.toJSON.call({toISOString:function(){return true}})}catch(v){}if(!l)Date.prototype.toJSON=function(){var a=Object(this),b;a:if(c(a))b=a;else{b=a.valueOf;if(typeof b==="function"&&(b=b.call(a),c(b)))break a;b=a.toString;if(typeof b==="function"&&(b=b.call(a),c(b)))break a;throw new TypeError;}if(typeof b==="number"&&
!isFinite(b))return null;b=a.toISOString;if(typeof b!="function")throw new TypeError("toISOString property is not callable");return b.call(a)};Date=function(a){function b(c,d,e,f,g,y,s){var l=arguments.length;return this instanceof a?(l=l==1&&String(c)===c?new a(b.parse(c)):l>=7?new a(c,d,e,f,g,y,s):l>=6?new a(c,d,e,f,g,y):l>=5?new a(c,d,e,f,g):l>=4?new a(c,d,e,f):l>=3?new a(c,d,e):l>=2?new a(c,d):l>=1?new a(c):new a,l.constructor=b,l):a.apply(this,arguments)}function c(a,b){var d=b>1?1:0;return e[b]+
Math.floor((a-1969+d)/4)-Math.floor((a-1901+d)/100)+Math.floor((a-1601+d)/400)+365*(a-1970)}var d=RegExp("^(\\d{4}|[+-]\\d{6})(?:-(\\d{2})(?:-(\\d{2})(?:T(\\d{2}):(\\d{2})(?::(\\d{2})(?:\\.(\\d{3}))?)?(Z|(?:([-+])(\\d{2}):(\\d{2})))?)?)?)?$"),e=[0,31,59,90,120,151,181,212,243,273,304,334,365],f;for(f in a)b[f]=a[f];b.now=a.now;b.UTC=a.UTC;b.prototype=a.prototype;b.prototype.constructor=b;b.parse=function(b){var e=d.exec(b);if(e){var f=Number(e[1]),g=Number(e[2]||1)-1,y=Number(e[3]||1)-1,l=Number(e[4]||
0),k=Number(e[5]||0),v=Number(e[6]||0),h=Number(e[7]||0),C=!e[4]||e[8]?0:Number(new a(1970,0)),p=e[9]==="-"?1:-1,q=Number(e[10]||0),e=Number(e[11]||0);if(l<(k>0||v>0||h>0?24:25)&&k<60&&v<60&&h<1E3&&g>-1&&g<12&&q<24&&e<60&&y>-1&&y<c(f,g+1)-c(f,g))if(f=((c(f,g)+y)*24+l+q*p)*60,f=((f+k+e*p)*60+v)*1E3+h+C,-864E13<=f&&f<=864E13)return f;return NaN}return a.parse.apply(this,arguments)};return b}(Date);if(!Date.now)Date.now=function(){return(new Date).getTime()};if("0".split(void 0,0).length){var p=String.prototype.split;
String.prototype.split=function(a,b){return a===void 0&&b===0?[]:p.apply(this,arguments)}}if("".substr&&"0b".substr(-1)!=="b"){var w=String.prototype.substr;String.prototype.substr=function(a,b){return w.call(this,a<0?(a=this.length+a)<0?0:a:a,b)}}l="\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||l.trim()){l="["+l+"]";var h=RegExp("^"+l+l+"*"),z=RegExp(l+l+"*$");String.prototype.trim=
function(){if(this===void 0||this===null)throw new TypeError("can't convert "+this+" to object");return String(this).replace(h,"").replace(z,"")}}var r=function(a){if(a==null)throw new TypeError("can't convert "+a+" to object");return Object(a)}});
(function(a){typeof define=="function"?define(a):typeof YUI=="function"?YUI.add("es5-sham",a):a()})(function(){function a(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(b){}}var b=Function.prototype.call,c=Object.prototype,d=b.bind(c.hasOwnProperty),e,g,f,m,j;if(j=d(c,"__defineGetter__"))e=b.bind(c.__defineGetter__),g=b.bind(c.__defineSetter__),f=b.bind(c.__lookupGetter__),m=b.bind(c.__lookupSetter__);if(!Object.getPrototypeOf)Object.getPrototypeOf=function(a){return a.__proto__||
(a.constructor?a.constructor.prototype:c)};if(!Object.getOwnPropertyDescriptor)Object.getOwnPropertyDescriptor=function(a,b){if(typeof a!="object"&&typeof a!="function"||a===null)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+a);if(d(a,b)){var e={enumerable:true,configurable:true};if(j){var g=a.__proto__;a.__proto__=c;var k=f(a,b),q=m(a,b);a.__proto__=g;if(k||q){if(k)e.get=k;if(q)e.set=q;return e}}e.value=a[b];return e}};if(!Object.getOwnPropertyNames)Object.getOwnPropertyNames=
function(a){return Object.keys(a)};if(!Object.create){var k;k=Object.prototype.__proto__===null||typeof document=="undefined"?function(){return{__proto__:null}}:function(){function a(){}var b=document.createElement("iframe"),c=document.body||document.documentElement;b.style.display="none";c.appendChild(b);b.src="javascript:";var d=b.contentWindow.Object.prototype;c.removeChild(b);b=null;delete d.constructor;delete d.hasOwnProperty;delete d.propertyIsEnumerable;delete d.isPrototypeOf;delete d.toLocaleString;
delete d.toString;delete d.valueOf;d.__proto__=null;a.prototype=d;return function(){return new a}}();Object.create=function(a,b){function c(){}var d;if(a===null)d=k();else{if(typeof a!=="object"&&typeof a!=="function")throw new TypeError("Object prototype may only be an Object or null");c.prototype=a;d=new c;d.__proto__=a}b!==void 0&&Object.defineProperties(d,b);return d}}if(Object.defineProperty){var b=a({}),q=typeof document=="undefined"||a(document.createElement("div"));if(!b||!q)var n=Object.defineProperty,
i=Object.defineProperties}if(!Object.defineProperty||n)Object.defineProperty=function(a,b,k){if(typeof a!="object"&&typeof a!="function"||a===null)throw new TypeError("Object.defineProperty called on non-object: "+a);if(typeof k!="object"&&typeof k!="function"||k===null)throw new TypeError("Property description must be an object: "+k);if(n)try{return n.call(Object,a,b,k)}catch(q){}if(d(k,"value"))if(j&&(f(a,b)||m(a,b))){var h=a.__proto__;a.__proto__=c;delete a[b];a[b]=k.value;a.__proto__=h}else a[b]=
k.value;else{if(!j)throw new TypeError("getters & setters can not be defined on this javascript engine");d(k,"get")&&e(a,b,k.get);d(k,"set")&&g(a,b,k.set)}return a};if(!Object.defineProperties||i)Object.defineProperties=function(a,b){if(i)try{return i.call(Object,a,b)}catch(c){}for(var e in b)d(b,e)&&e!="__proto__"&&Object.defineProperty(a,e,b[e]);return a};if(!Object.seal)Object.seal=function(a){return a};if(!Object.freeze)Object.freeze=function(a){return a};try{Object.freeze(function(){})}catch(o){Object.freeze=
function(a){return function(b){return typeof b=="function"?b:a(b)}}(Object.freeze)}if(!Object.preventExtensions)Object.preventExtensions=function(a){return a};if(!Object.isSealed)Object.isSealed=function(){return false};if(!Object.isFrozen)Object.isFrozen=function(){return false};if(!Object.isExtensible)Object.isExtensible=function(a){if(Object(a)!==a)throw new TypeError;for(var b="";d(a,b);)b+="?";a[b]=true;var c=d(a,b);delete a[b];return c}});
(function(){function a(a){var c,d,g,k=a=="json";if(k||a=="json-stringify"||a=="json-parse"){if(a=="json-stringify"||k){if(c=typeof f.stringify=="function"&&r){(g=function(){return 1}).toJSON=g;try{c=f.stringify(0)==="0"&&f.stringify(new Number)==="0"&&f.stringify(new String)=='""'&&f.stringify(b)===e&&f.stringify(e)===e&&f.stringify()===e&&f.stringify(g)==="1"&&f.stringify([g])=="[1]"&&f.stringify([e])=="[null]"&&f.stringify(null)=="null"&&f.stringify([e,b,null])=="[null,null,null]"&&f.stringify({A:[g,
true,false,null,"\x00\u0008\n\u000c\r\t"]})=='{"A":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'&&f.stringify(null,g)==="1"&&f.stringify([1,2],null,1)=="[\n 1,\n 2\n]"&&f.stringify(new Date(-864E13))=='"-271821-04-20T00:00:00.000Z"'&&f.stringify(new Date(864E13))=='"+275760-09-13T00:00:00.000Z"'&&f.stringify(new Date(-621987552E5))=='"-000001-01-01T00:00:00.000Z"'&&f.stringify(new Date(-1))=='"1969-12-31T23:59:59.999Z"'}catch(h){c=false}}if(!k)return c}if(a=="json-parse"||k){if(typeof f.parse=="function")try{if(f.parse("0")===
0&&!f.parse(false)&&(g=f.parse('{"A":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'),d=g.A.length==5&&g.A[0]==1)){try{d=!f.parse('"\t"')}catch(q){}if(d)try{d=f.parse("01")!=1}catch(E){}}}catch(t){d=false}if(!k)return d}return c&&d}}var b={}.toString,c,d,e,g=typeof define==="function"&&define.amd,f=!g&&typeof exports=="object"&&exports;if(f||g)if(typeof JSON=="object"&&JSON)g?f=JSON:(f.stringify=JSON.stringify,f.parse=JSON.parse);else{if(g)f=this.JSON={}}else f=this.JSON||(this.JSON={});var m,j,k,
q,n,i,o,l,v,p,w,h,z,r=new Date(-3509827334573292),x,u,A;try{r=r.getUTCFullYear()==-109252&&r.getUTCMonth()===0&&r.getUTCDate()==1&&r.getUTCHours()==10&&r.getUTCMinutes()==37&&r.getUTCSeconds()==6&&r.getUTCMilliseconds()==708}catch(D){}if(!a("json")){if(!r)x=Math.floor,u=[0,31,59,90,120,151,181,212,243,273,304,334],A=function(a,b){return u[b]+365*(a-1970)+x((a-1969+(b=+(b>1)))/4)-x((a-1901+b)/100)+x((a-1601+b)/400)};if(!(c={}.hasOwnProperty))c=function(a){var d={},e;(d.__proto__=null,d.__proto__={toString:1},
d).toString!=b?c=function(a){var b=this.__proto__,a=a in(this.__proto__=null,this);this.__proto__=b;return a}:(e=d.constructor,c=function(a){var b=(this.constructor||e).prototype;return a in this&&!(a in b&&this[a]===b[a])});d=null;return c.call(this,a)};d=function(a,d){var e=0,f,g,k;(f=function(){this.valueOf=0}).prototype.valueOf=0;g=new f;for(k in g)c.call(g,k)&&e++;f=g=null;e?e=e==2?function(a,d){var e={},f=b.call(a)=="[object Function]",g;for(g in a)!(f&&g=="prototype")&&!c.call(e,g)&&(e[g]=
1)&&c.call(a,g)&&d(g)}:function(a,d){var e=b.call(a)=="[object Function]",f,g;for(f in a)!(e&&f=="prototype")&&c.call(a,f)&&!(g=f==="constructor")&&d(f);(g||c.call(a,f="constructor"))&&d(f)}:(g="valueOf,toString,toLocaleString,propertyIsEnumerable,isPrototypeOf,hasOwnProperty,constructor".split(","),e=function(a,d){var e=b.call(a)=="[object Function]",f;for(f in a)!(e&&f=="prototype")&&c.call(a,f)&&d(f);for(e=g.length;f=g[--e];c.call(a,f)&&d(f));});return e(a,d)};if(!a("json-stringify"))m={"\\":"\\\\",
'"':'\\"',"\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},j=function(a,b){return("000000"+(b||0)).slice(-a)},k=function(a){for(var b='"',c=0,d;d=a.charAt(c);c++)b+='\\"\u0008\u000c\n\r\t'.indexOf(d)>-1?m[d]:m[d]=d<" "?"\\u00"+j(2,d.charCodeAt(0).toString(16)):d;return b+'"'},q=function(a,f,g,h,l,n,o){var i=f[a],t,m,v,p,r,u,z,w,B;if(typeof i=="object"&&i)if(t=b.call(i),t=="[object Date]"&&!c.call(i,"toJSON"))if(i>-1/0&&i<1/0){if(A){v=x(i/864E5);for(t=x(v/365.2425)+1970-1;A(t+1,0)<=
v;t++);for(m=x((v-A(t,0))/30.42);A(t,m+1)<=v;m++);v=1+v-A(t,m);p=(i%864E5+864E5)%864E5;r=x(p/36E5)%24;u=x(p/6E4)%60;z=x(p/1E3)%60;p%=1E3}else t=i.getUTCFullYear(),m=i.getUTCMonth(),v=i.getUTCDate(),r=i.getUTCHours(),u=i.getUTCMinutes(),z=i.getUTCSeconds(),p=i.getUTCMilliseconds();i=(t<=0||t>=1E4?(t<0?"-":"+")+j(6,t<0?-t:t):j(4,t))+"-"+j(2,m+1)+"-"+j(2,v)+"T"+j(2,r)+":"+j(2,u)+":"+j(2,z)+"."+j(3,p)+"Z"}else i=null;else if(typeof i.toJSON=="function"&&(t!="[object Number]"&&t!="[object String]"&&t!=
"[object Array]"||c.call(i,"toJSON")))i=i.toJSON(a);g&&(i=g.call(f,a,i));if(i===null)return"null";t=b.call(i);if(t=="[object Boolean]")return""+i;else if(t=="[object Number]")return i>-1/0&&i<1/0?""+i:"null";else if(t=="[object String]")return k(i);if(typeof i=="object"){for(a=o.length;a--;)if(o[a]===i)throw TypeError();o.push(i);w=[];f=n;n+=l;if(t=="[object Array]"){for(m=0,a=i.length;m<a;B||(B=true),m++)t=q(m,i,g,h,l,n,o),w.push(t===e?"null":t);a=B?l?"[\n"+n+w.join(",\n"+n)+"\n"+f+"]":"["+w.join(",")+
"]":"[]"}else d(h||i,function(a){var b=q(a,i,g,h,l,n,o);b!==e&&w.push(k(a)+":"+(l?" ":"")+b);B||(B=true)}),a=B?l?"{\n"+n+w.join(",\n"+n)+"\n"+f+"}":"{"+w.join(",")+"}":"{}";o.pop();return a}},f.stringify=function(a,c,d){var e,f,g,k,i,h;if(typeof c=="function"||typeof c=="object"&&c)if(b.call(c)=="[object Function]")f=c;else if(b.call(c)=="[object Array]"){g={};for(k=0,i=c.length;k<i;h=c[k++],(b.call(h)=="[object String]"||b.call(h)=="[object Number]")&&(g[h]=1));}if(d)if(b.call(d)=="[object Number]"){if((d-=
d%1)>0)for(e="",d>10&&(d=10);e.length<d;e+=" ");}else b.call(d)=="[object String]"&&(e=d.length<=10?d:d.slice(0,10));return q("",(h={},h[""]=a,h),f,g,e,"",[])};if(!a("json-parse"))n=String.fromCharCode,i={"\\":"\\",'"':'"',"/":"/",b:"\u0008",t:"\t",n:"\n",f:"\u000c",r:"\r"},o=function(){h=z=null;throw SyntaxError();},l=function(){for(var a=z,b=a.length,c,d,e,f,g;h<b;)if(c=a.charAt(h),"\t\r\n ".indexOf(c)>-1)h++;else if("{}[]:,".indexOf(c)>-1)return h++,c;else{if(c=='"'){for(d="@",h++;h<b;)if(c=a.charAt(h),
c<" ")o();else if(c=="\\")if(c=a.charAt(++h),'\\"/btnfr'.indexOf(c)>-1)d+=i[c],h++;else if(c=="u"){e=++h;for(f=h+4;h<f;h++)c=a.charAt(h),c>="0"&&c<="9"||c>="a"&&c<="f"||c>="A"&&c<="F"||o();d+=n("0x"+a.slice(e,h))}else o();else{if(c=='"')break;d+=c;h++}if(a.charAt(h)=='"')return h++,d}else{e=h;c=="-"&&(g=true,c=a.charAt(++h));if(c>="0"&&c<="9"){for(c=="0"&&(c=a.charAt(h+1),c>="0"&&c<="9")&&o();h<b&&(c=a.charAt(h),c>="0"&&c<="9");h++);if(a.charAt(h)=="."){for(f=++h;f<b&&(c=a.charAt(f),c>="0"&&c<="9");f++);
f==h&&o();h=f}c=a.charAt(h);if(c=="e"||c=="E"){c=a.charAt(++h);(c=="+"||c=="-")&&h++;for(f=h;f<b&&(c=a.charAt(f),c>="0"&&c<="9");f++);f==h&&o();h=f}return+a.slice(e,h)}g&&o();if(a.slice(h,h+4)=="true")return h+=4,true;else if(a.slice(h,h+5)=="false")return h+=5,false;else if(a.slice(h,h+4)=="null")return h+=4,null}o()}return"$"},v=function(a){var b,c;a=="$"&&o();if(typeof a=="string"){if(a.charAt(0)=="@")return a.slice(1);if(a=="["){for(b=[];;c||(c=true)){a=l();if(a=="]")break;c&&(a==","?(a=l(),a==
"]"&&o()):o());a==","&&o();b.push(v(a))}return b}else if(a=="{"){for(b={};;c||(c=true)){a=l();if(a=="}")break;c&&(a==","?(a=l(),a=="}"&&o()):o());(a==","||typeof a!="string"||a.charAt(0)!="@"||l()!=":")&&o();b[a.slice(1)]=v(l())}return b}o()}return a},w=function(a,b,c){c=p(a,b,c);c===e?delete a[b]:a[b]=c},p=function(a,c,e){var f=a[c],g;if(typeof f=="object"&&f)if(b.call(f)=="[object Array]")for(g=f.length;g--;)w(f,g,e);else d(f,function(a){w(f,a,e)});return e.call(a,c,f)},f.parse=function(a,c){var d,
e;h=0;z=a;d=v(l());l()!="$"&&o();h=z=null;return c&&b.call(c)=="[object Function]"?p((e={},e[""]=d,e),"",c):d}}g&&define(function(){return f})}).call(this);
(function(){function a(){this._object=g&&!j?new g:new window.ActiveXObject("Microsoft.XMLHTTP");this._listeners=[]}function b(){return new a}function c(a){b.onreadystatechange&&b.onreadystatechange.apply(a);a.dispatchEvent({type:"readystatechange",bubbles:false,cancelable:false,timeStamp:new Date+0})}function d(a){try{a.responseText=a._object.responseText}catch(b){}try{var c=a._object,d=c.responseXML,e=c.responseText;if(m&&e&&d&&!d.documentElement&&c.getResponseHeader("Content-Type").match(/[^\/]+\/[^\+]+\+xml/))d=
new window.ActiveXObject("Microsoft.XMLDOM"),d.async=false,d.validateOnParse=false,d.loadXML(e);a.responseXML=d&&(m&&d.parseError!==0||!d.documentElement||d.documentElement&&d.documentElement.tagName=="parsererror")?null:d}catch(f){}try{a.status=a._object.status}catch(g){}try{a.statusText=a._object.statusText}catch(j){}}function e(a){a._object.onreadystatechange=new window.Function}var g=window.XMLHttpRequest,f=!!window.controllers,m=!!window.document.namespaces,j=m&&window.navigator.userAgent.match(/MSIE 7.0/);
b.prototype=a.prototype;if(f&&g.wrapped)b.wrapped=g.wrapped;b.UNSENT=0;b.OPENED=1;b.HEADERS_RECEIVED=2;b.LOADING=3;b.DONE=4;b.prototype.UNSENT=b.UNSENT;b.prototype.OPENED=b.OPENED;b.prototype.HEADERS_RECEIVED=b.HEADERS_RECEIVED;b.prototype.LOADING=b.LOADING;b.prototype.DONE=b.DONE;b.prototype.readyState=b.UNSENT;b.prototype.responseText="";b.prototype.responseXML=null;b.prototype.status=0;b.prototype.statusText="";b.prototype.priority="NORMAL";b.prototype.onreadystatechange=null;b.onreadystatechange=
null;b.onopen=null;b.onsend=null;b.onabort=null;b.prototype.open=function(a,g,n,i,o){var l=a.toLowerCase();if(l=="connect"||l=="trace"||l=="track")throw Error(18);delete this._headers;arguments.length<3&&(n=true);this._async=n;var j=this,p=this.readyState,w=null;m&&n&&(w=function(){p!=b.DONE&&(e(j),j.abort())},window.attachEvent("onunload",w));b.onopen&&b.onopen.apply(this,arguments);arguments.length>4?this._object.open(a,g,n,i,o):arguments.length>3?this._object.open(a,g,n,i):this._object.open(a,
g,n);this.readyState=b.OPENED;c(this);this._object.onreadystatechange=function(){if(!f||n)if(j.readyState=j._object.readyState,d(j),j._aborted)j.readyState=b.UNSENT;else if(j.readyState==b.DONE)delete j._data,e(j),m&&n&&window.detachEvent("onunload",w),p!=j.readyState&&c(j),p=j.readyState}};b.prototype.send=function(a){b.onsend&&b.onsend.apply(this,arguments);arguments.length||(a=null);a&&a.nodeType&&(a=window.XMLSerializer?(new window.XMLSerializer).serializeToString(a):a.xml,this._headers["Content-Type"]||
this._object.setRequestHeader("Content-Type","application/xml"));this._data=a;this._object.send(this._data);if(f&&!this._async){this.readyState=b.OPENED;for(d(this);this.readyState<b.DONE;)if(this.readyState++,c(this),this._aborted)break}};b.prototype.abort=function(){b.onabort&&b.onabort.apply(this,arguments);if(this.readyState>b.UNSENT)this._aborted=true;this._object.abort();e(this);this.readyState=b.UNSENT;delete this._data};b.prototype.getAllResponseHeaders=function(){return this._object.getAllResponseHeaders()};
b.prototype.getResponseHeader=function(a){return this._object.getResponseHeader(a)};b.prototype.setRequestHeader=function(a,b){if(!this._headers)this._headers={};this._headers[a]=b;return this._object.setRequestHeader(a,b)};b.prototype.addEventListener=function(a,b,c){for(var d=0,e;e=this._listeners[d];d++)if(e[0]==a&&e[1]==b&&e[2]==c)return;this._listeners.push([a,b,c])};b.prototype.removeEventListener=function(a,b,c){for(var d=0,e;e=this._listeners[d];d++)if(e[0]==a&&e[1]==b&&e[2]==c)break;e&&this._listeners.splice(d,
1)};b.prototype.dispatchEvent=function(a){a={type:a.type,target:this,currentTarget:this,eventPhase:2,bubbles:a.bubbles,cancelable:a.cancelable,timeStamp:a.timeStamp,stopPropagation:function(){},preventDefault:function(){},initEvent:function(){}};a.type=="readystatechange"&&this.onreadystatechange&&(this.onreadystatechange.handleEvent||this.onreadystatechange).apply(this,[a]);for(var b=0,c;c=this._listeners[b];b++)c[0]==a.type&&!c[2]&&(c[1].handleEvent||c[1]).apply(this,[a])};b.prototype.toString=
function(){return"[object XMLHttpRequest]"};b.toString=function(){return"[XMLHttpRequest]"};if(!window.Function.prototype.apply)window.Function.prototype.apply=function(a,b){b||(b=[]);a.__func=this;a.__func(b[0],b[1],b[2],b[3],b[4]);delete a.__func};window.XMLHttpRequest=b})();
(function(){var a=function(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.concat(Array.prototype.slice.call(arguments,0));a.apply(b,c)}};if(!window.console)window.console={};var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};if(!b.debug)b.debug=b.log;if(!b.info)b.info=b.log;if(!b.warn)b.warn=b.log;if(!b.error)b.error=
b.log;if(window.__consoleShimTest__!=null||eval("/*@cc_on @_jscript_version <= 9@*/"))c=function(a){var c,d,m,a=Array.prototype.slice.call(arguments,0);m=a.shift();d=a.length;if(d>1&&window.__consoleShimTest__!==false){typeof a[0]!="string"&&(a.unshift("%o"),d+=1);for(c=(c=a[0].match(/%[a-z]/g))?c.length+1:1;c<d;c+=1)a[0]+=" %o"}Function.apply.call(m,b,a)},b.log=a(c,window,b.log),b.debug=a(c,window,b.debug),b.info=a(c,window,b.info),b.warn=a(c,window,b.warn),b.error=a(c,window,b.error);b.assert||
(b.assert=function(){var a=Array.prototype.slice.call(arguments,0);a.shift()||(a[0]="Assertion failed: "+a[0],b.error.apply(b,a))});if(!b.dir)b.dir=b.log;if(!b.dirxml)b.dirxml=b.log;if(!b.exception)b.exception=b.error;if(!b.time||!b.timeEnd){var d={};b.time=function(a){d[a]=(new Date).getTime()};b.timeEnd=function(a){var c=d[a];c&&(b.log(a+": "+((new Date).getTime()-c)+"ms"),delete d[a])}}b.table||(b.table=function(a,c){var d,m,j,k,q;if(a&&a instanceof Array&&a.length){if(!c||!(c instanceof Array))for(d in c=
[],a[0])a[0].hasOwnProperty(d)&&c.push(d);for(d=0,m=a.length;d<m;d+=1){j=[];for(k=0,q=c.length;k<q;k+=1)j.push(a[d][c[k]]);Function.apply.call(b.log,b,j)}}});b.clear||(b.clear=function(){});b.trace||(b.trace=function(){});b.group||(b.group=function(){});b.groupCollapsed||(b.groupCollapsed=function(){});b.groupEnd||(b.groupEnd=function(){});b.timeStamp||(b.timeStamp=function(){});b.profile||(b.profile=function(){});b.profileEnd||(b.profileEnd=function(){});b.count||(b.count=function(){})})();
function printStackTrace(a){var a=a||{guess:true},b=a.e||null,a=!!a.guess,c=new printStackTrace.implementation,b=c.run(b);return a?c.guessAnonymousFunctions(b):b}if(typeof module!=="undefined"&&module.exports)module.exports=printStackTrace;printStackTrace.implementation=function(){};
printStackTrace.implementation.prototype={run:function(a,b){a=a||this.createException();b=b||this.mode(a);return b==="other"?this.other(arguments.callee):this[b](a)},createException:function(){try{this.undef()}catch(a){return a}},mode:function(a){if(a.arguments&&a.stack)return"chrome";else if(a.stack&&a.sourceURL)return"safari";else if(a.stack&&a.number)return"ie";else if(typeof a.message==="string"&&typeof window!=="undefined"&&window.opera)return!a.stacktrace?"opera9":a.message.indexOf("\n")>-1&&
a.message.split("\n").length>a.stacktrace.split("\n").length?"opera9":!a.stack?"opera10a":a.stacktrace.indexOf("called from line")<0?"opera10b":"opera11";else if(a.stack)return"firefox";return"other"},instrumentFunction:function(a,b,c){var a=a||window,d=a[b];a[b]=function(){c.call(this,printStackTrace().slice(4));return a[b]._instrumented.apply(this,arguments)};a[b]._instrumented=d},deinstrumentFunction:function(a,b){if(a[b].constructor===Function&&a[b]._instrumented&&a[b]._instrumented.constructor===
Function)a[b]=a[b]._instrumented},chrome:function(a){a=(a.stack+"\n").replace(/^\S[^\(]+?[\n$]/gm,"").replace(/^\s+(at eval )?at\s+/gm,"").replace(/^([^\(]+?)([\n$])/gm,"{anonymous}()@$1$2").replace(/^Object.<anonymous>\s*\(([^\)]+)\)/gm,"{anonymous}()@$1").split("\n");a.pop();return a},safari:function(a){return a.stack.replace(/\[native code\]\n/m,"").replace(/^(?=\w+Error\:).*$\n/m,"").replace(/^@/gm,"{anonymous}()@").split("\n")},ie:function(a){return a.stack.replace(/at Anonymous function /gm,
"{anonymous}()@").replace(/^(?=\w+Error\:).*$\n/m,"").replace(/^.*at (\w+) \(([^\)]+)\)$/gm,"$1@$2").split("\n")},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,"").replace(/^[\(@]/gm,"{anonymous}()@").split("\n")},opera11:function(a){for(var b=/^.*line (\d+), column (\d+)(?: in (.+))? in (\S+):$/,a=a.stacktrace.split("\n"),c=[],d=0,e=a.length;d<e;d+=2){var g=b.exec(a[d]);if(g){var f=g[4]+":"+g[1]+":"+g[2],g=g[3]||"global code",g=g.replace(/<anonymous function: (\S+)>/,"$1").replace(/<anonymous function>/,
"{anonymous}");c.push(g+"@"+f+" -- "+a[d+1].replace(/^\s+/,""))}}return c},opera10b:function(a){for(var b=/^(.*)@(.+):(\d+)$/,a=a.stacktrace.split("\n"),c=[],d=0,e=a.length;d<e;d++){var g=b.exec(a[d]);g&&c.push((g[1]?g[1]+"()":"global code")+"@"+g[2]+":"+g[3])}return c},opera10a:function(a){for(var b=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i,a=a.stacktrace.split("\n"),c=[],d=0,e=a.length;d<e;d+=2){var g=b.exec(a[d]);g&&c.push((g[3]||"{anonymous}")+"()@"+g[2]+":"+g[1]+" -- "+a[d+
1].replace(/^\s+/,""))}return c},opera9:function(a){for(var b=/Line (\d+).*script (?:in )?(\S+)/i,a=a.message.split("\n"),c=[],d=2,e=a.length;d<e;d+=2){var g=b.exec(a[d]);g&&c.push("{anonymous}()@"+g[2]+":"+g[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,c=[],d,e;a&&a.arguments&&c.length<10;)d=b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",e=Array.prototype.slice.call(a.arguments||[]),c[c.length]=d+"("+this.stringifyArguments(e)+
")",a=a.caller;return c},stringifyArguments:function(a){for(var b=[],c=Array.prototype.slice,d=0;d<a.length;++d){var e=a[d];e===void 0?b[d]="undefined":e===null?b[d]="null":e.constructor&&(e.constructor===Array?b[d]=e.length<3?"["+this.stringifyArguments(e)+"]":"["+this.stringifyArguments(c.call(e,0,1))+"..."+this.stringifyArguments(c.call(e,-1))+"]":e.constructor===Object?b[d]="#object":e.constructor===Function?b[d]="#function":e.constructor===String?b[d]='"'+e+'"':e.constructor===Number&&(b[d]=
e))}return b.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();if(b)try{return b.open("GET",a,false),b.send(null),b.responseText}catch(c){}return""},createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<b.length;c++)try{return a=b[c](),this.createXMLHTTPObject=b[c],a}catch(d){}},
isSameDomain:function(a){return typeof location!=="undefined"&&a.indexOf(location.hostname)!==-1},getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));return this.sourceCache[a]},guessAnonymousFunctions:function(a){for(var b=0;b<a.length;++b){var c=/^(.*?)(?::(\d+))(?::(\d+))?(?: -- .+)?$/,d=a[b],e=/\{anonymous\}\(.*\)@(.*)/.exec(d);if(e){var g=c.exec(e[1]);g&&(c=g[1],e=g[2],g=g[3]||0,c&&this.isSameDomain(c)&&e&&(c=this.guessAnonymousFunction(c,e,g),a[b]=d.replace("{anonymous}",
c)))}}return a},guessAnonymousFunction:function(a,b){var c;try{c=this.findFunctionName(this.getSource(a),b)}catch(d){c="getSource failed with url: "+a+", exception: "+d.toString()}return c},findFunctionName:function(a,b){for(var c=/function\s+([^(]*?)\s*\(([^)]*)\)/,d=/['"]?([$_A-Za-z][$_A-Za-z0-9]*)['"]?\s*[:=]\s*function\b/,e=/['"]?([$_A-Za-z][$_A-Za-z0-9]*)['"]?\s*[:=]\s*(?:eval|new Function)\b/,g="",f,m=Math.min(b,20),j,k=0;k<m;++k)if(f=a[b-k-1],j=f.indexOf("//"),j>=0&&(f=f.substr(0,j)),f){g=
f+g;if((f=d.exec(g))&&f[1])return f[1];if((f=c.exec(g))&&f[1])return f[1];if((f=e.exec(g))&&f[1])return f[1]}return"(?)"}};(function(){if(!Array.from)Array.from=function(a){for(var a=Object(a),b=[],c=0,d=a.length>>>0;c<d;c++)c in a&&(b[c]=a[c]);return b};if(!Array.of)Array.of=function(){return Array.prototype.slice.call(arguments)}})();
(function(){if(!Math.acosh)Math.acosh=function(a){return Math.log(a+Math.sqrt(a*a-1))};if(!Math.asinh)Math.asinh=function(a){return Math.log(a+Math.sqrt(a*a+1))};if(!Math.atanh)Math.atanh=function(a){return 0.5*Math.log((1+a)/(1-a))};if(!Math.cosh)Math.cosh=function(a){a<0&&(a=-a);return a>21?Math.exp(a)/2:(Math.exp(a)+Math.exp(-a))/2};if(!Math.sinh)Math.sinh=function(a){return(Math.exp(a)-Math.exp(-a))/2};if(!Math.tanh)Math.tanh=function(a){return(Math.exp(a)-Math.exp(-a))/(Math.exp(a)+Math.exp(-a))};
if(!Math.expm1)Math.expm1=function(a){for(var b=0,c=1;c<50;c++){for(var d=Math.pow(a,c),e=1,g=2;g<=c;g++)e*=g;b+=d/e}return b};if(!Math.hypot)Math.hypot=function(a,b){return Math.sqrt(a*a+b*b)||0};if(!Math.log2)Math.log2=function(a){return Math.log(a)*(1/Math.LN2)};if(!Math.log10)Math.log10=function(a){return Math.log(a)*(1/Math.LN10)};if(!Math.log1p)Math.log1p=function(a){var b=0;if(a<=-1)return-Infinity;if(a<0||a>1)return Math.log(1+a);for(var c=1;c<50;c++)c%2===0?b-=Math.pow(a,c)/c:b+=Math.pow(a,
c)/c;return b};if(!Math.sign)Math.sign=function(a){a=+a;return a===0?a:Object.is(a,NaN)?a:a<0?-1:1};if(!Math.trunc)Math.trunc=function(a){return~~a}})();
(function(){if(!Number.isFinite)Number.isFinite=function(a){return typeof a==="number"&&isFinite(a)};if(!Number.isInteger)Number.isInteger=function(a){return Number.isFinite(a)&&a>=-9007199254740992&&a<=9007199254740992&&Math.floor(a)===a};if(!Number.isNaN)Number.isNaN=function(a){return Object.is(a,NaN)};if(!Number.toInteger)Number.toInteger=function(a){a=+a;return Object.is(a,NaN)?0:a===0||!Number.isFinite(a)?a:Math.sign(a)*Math.floor(Math.abs(a))}})();
(function(){if(!Object.getOwnPropertyDescriptors)Object.getOwnPropertyDescriptors=function(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};if(!Object.getPropertyDescriptor)Object.getPropertyDescriptor=function(a,b){for(var c=Object.getOwnPropertyDescriptor(a,b),d=Object.getPrototypeOf(a);c===void 0&&d!==null;)c=Object.getOwnPropertyDescriptor(d,b),d=Object.getPrototypeOf(d);return c};if(!Object.getPropertyNames)Object.getPropertyNames=
function(a){for(var b=Object.getOwnPropertyNames(a),a=Object.getPrototypeOf(a),c=function(a){b.indexOf(a)===-1&&b.push(a)};a!==null;)Object.getOwnPropertyNames(a).forEach(c),a=Object.getPrototypeOf(a);return b};if(!Object.is)Object.is=function(a,b){return a===b?a===0?1/a===1/b:true:a!==a&&b!==b};if(!Object.isnt)Object.isnt=function(a,b){return!Object.is(a,b)}})();
(function(){if(!String.prototype.repeat)String.prototype.repeat=function(a){if(a<1)return"";if(a%2)return this.repeat(a-1)+this;a=this.repeat(a/2);return a+a};if(!String.prototype.startsWith)String.prototype.startsWith=function(a,b){var c=this.toString(),d=b===void 0?0:Number.toInteger(b),e=c.length,d=Math.min(Math.max(d,0),e);return a.length+d>e?false:"".indexOf.call(c,a,d)===d};if(!String.prototype.endsWith)String.prototype.endsWith=function(a,b){var c=this.toString(),d=c.length,e=b===void 0?d:
Number.toInteger(b),d=Math.min(Math.max(e,0),d)-a.length;return d<0?false:"".indexOf.call(c,a,d)===d};if(!String.prototype.contains)String.prototype.contains=function(a,b){return"".indexOf.call(this,a,b)!==-1}})();
