'use strict';function printStackTrace(a){var a=a||{guess:true},b=a.e||null,a=!!a.guess,c=new printStackTrace.implementation,b=c.run(b);return a?c.guessAnonymousFunctions(b):b}if(typeof module!=="undefined"&&module.exports)module.exports=printStackTrace;printStackTrace.implementation=function(){};
printStackTrace.implementation.prototype={run:function(a,b){a=a||this.createException();b=b||this.mode(a);return b==="other"?this.other(arguments.callee):this[b](a)},createException:function(){try{this.undef()}catch(a){return a}},mode:function(a){if(a.arguments&&a.stack)return"chrome";else if(a.stack&&a.sourceURL)return"safari";else if(a.stack&&a.number)return"ie";else if(typeof a.message==="string"&&typeof window!=="undefined"&&window.opera)return!a.stacktrace?"opera9":a.message.indexOf("\n")>-1&&
a.message.split("\n").length>a.stacktrace.split("\n").length?"opera9":!a.stack?"opera10a":a.stacktrace.indexOf("called from line")<0?"opera10b":"opera11";else if(a.stack)return"firefox";return"other"},instrumentFunction:function(a,b,c){var a=a||window,d=a[b];a[b]=function(){c.call(this,printStackTrace().slice(4));return a[b]._instrumented.apply(this,arguments)};a[b]._instrumented=d},deinstrumentFunction:function(a,b){if(a[b].constructor===Function&&a[b]._instrumented&&a[b]._instrumented.constructor===
Function)a[b]=a[b]._instrumented},chrome:function(a){a=(a.stack+"\n").replace(/^\S[^\(]+?[\n$]/gm,"").replace(/^\s+(at eval )?at\s+/gm,"").replace(/^([^\(]+?)([\n$])/gm,"{anonymous}()@$1$2").replace(/^Object.<anonymous>\s*\(([^\)]+)\)/gm,"{anonymous}()@$1").split("\n");a.pop();return a},safari:function(a){return a.stack.replace(/\[native code\]\n/m,"").replace(/^(?=\w+Error\:).*$\n/m,"").replace(/^@/gm,"{anonymous}()@").split("\n")},ie:function(a){return a.stack.replace(/at Anonymous function /gm,
"{anonymous}()@").replace(/^(?=\w+Error\:).*$\n/m,"").replace(/^.*at (\w+) \(([^\)]+)\)$/gm,"$1@$2").split("\n")},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,"").replace(/^[\(@]/gm,"{anonymous}()@").split("\n")},opera11:function(a){for(var b=/^.*line (\d+), column (\d+)(?: in (.+))? in (\S+):$/,a=a.stacktrace.split("\n"),c=[],d=0,f=a.length;d<f;d+=2){var e=b.exec(a[d]);if(e){var g=e[4]+":"+e[1]+":"+e[2],e=e[3]||"global code",e=e.replace(/<anonymous function: (\S+)>/,"$1").replace(/<anonymous function>/,
"{anonymous}");c.push(e+"@"+g+" -- "+a[d+1].replace(/^\s+/,""))}}return c},opera10b:function(a){for(var b=/^(.*)@(.+):(\d+)$/,a=a.stacktrace.split("\n"),c=[],d=0,f=a.length;d<f;d++){var e=b.exec(a[d]);e&&c.push((e[1]?e[1]+"()":"global code")+"@"+e[2]+":"+e[3])}return c},opera10a:function(a){for(var b=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i,a=a.stacktrace.split("\n"),c=[],d=0,f=a.length;d<f;d+=2){var e=b.exec(a[d]);e&&c.push((e[3]||"{anonymous}")+"()@"+e[2]+":"+e[1]+" -- "+a[d+
1].replace(/^\s+/,""))}return c},opera9:function(a){for(var b=/Line (\d+).*script (?:in )?(\S+)/i,a=a.message.split("\n"),c=[],d=2,f=a.length;d<f;d+=2){var e=b.exec(a[d]);e&&c.push("{anonymous}()@"+e[2]+":"+e[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,c=[],d,f;a&&a.arguments&&c.length<10;)d=b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",f=Array.prototype.slice.call(a.arguments||[]),c[c.length]=d+"("+this.stringifyArguments(f)+
")",a=a.caller;return c},stringifyArguments:function(a){for(var b=[],c=Array.prototype.slice,d=0;d<a.length;++d){var f=a[d];f===void 0?b[d]="undefined":f===null?b[d]="null":f.constructor&&(f.constructor===Array?b[d]=f.length<3?"["+this.stringifyArguments(f)+"]":"["+this.stringifyArguments(c.call(f,0,1))+"..."+this.stringifyArguments(c.call(f,-1))+"]":f.constructor===Object?b[d]="#object":f.constructor===Function?b[d]="#function":f.constructor===String?b[d]='"'+f+'"':f.constructor===Number&&(b[d]=
f))}return b.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();if(b)try{return b.open("GET",a,false),b.send(null),b.responseText}catch(c){}return""},createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<b.length;c++)try{return a=b[c](),this.createXMLHTTPObject=b[c],a}catch(d){}},
isSameDomain:function(a){return typeof location!=="undefined"&&a.indexOf(location.hostname)!==-1},getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));return this.sourceCache[a]},guessAnonymousFunctions:function(a){for(var b=0;b<a.length;++b){var c=/^(.*?)(?::(\d+))(?::(\d+))?(?: -- .+)?$/,d=a[b],f=/\{anonymous\}\(.*\)@(.*)/.exec(d);if(f){var e=c.exec(f[1]);e&&(c=e[1],f=e[2],e=e[3]||0,c&&this.isSameDomain(c)&&f&&(c=this.guessAnonymousFunction(c,f,e),a[b]=d.replace("{anonymous}",
c)))}}return a},guessAnonymousFunction:function(a,b){var c;try{c=this.findFunctionName(this.getSource(a),b)}catch(d){c="getSource failed with url: "+a+", exception: "+d.toString()}return c},findFunctionName:function(a,b){for(var c=/function\s+([^(]*?)\s*\(([^)]*)\)/,d=/['"]?([$_A-Za-z][$_A-Za-z0-9]*)['"]?\s*[:=]\s*function\b/,f=/['"]?([$_A-Za-z][$_A-Za-z0-9]*)['"]?\s*[:=]\s*(?:eval|new Function)\b/,e="",g,j=Math.min(b,20),h,i=0;i<j;++i)if(g=a[b-i-1],h=g.indexOf("//"),h>=0&&(g=g.substr(0,h)),g){e=
g+e;if((g=d.exec(e))&&g[1])return g[1];if((g=c.exec(e))&&g[1])return g[1];if((g=f.exec(e))&&g[1])return g[1]}return"(?)"}};
